### ISSUE TITLE
17de79cc3ec459f5660616573d6edd0b2288b664 not working

### ISSUE THREAD

**Issue by cbean** [pali/igmpproxy#11]
I tested version 17de79cc3ec459f5660616573d6edd0b2288b664 and it does not work.

It seems quickleave is needed for Telekom IPTV (Entertain).

**Comment by cbean** [comment]
This is the patch-set I use:

## README

This patchset is against igmpproxy-0.1.

Project Homepage:   http://sourceforge.net/projects/igmpproxy/

## Patchset Numbering Scheme

UPSTREM
000-100   upstream committed

FIXES
100-200   fixes from http://wl500g.googlecode.com
200-300   fixes from T-Labs, Deutsche Telekom

## Individual Patch Descriptions:

Patch:  001_Restrict_igmp_reports_for_downstream_interfaces_(wrt_#2833339).patch
From:   Grinch grinch79@users.sourceforge.net
Desc:   Restrict igmp reports for downstream interfaces (wrt #2833339)

Patch:  002_Send_IGMP_packets_with_IP_Router_Alert_option_[RFC_2113]_included_in_IP_header.patch
From:   Evgeny Yurchenko evg.yurch@rogers.com
Desc:   Send IGMP packets with IP Router Alert option [RFC 2113] included in IP header

Patch:  003_Change_default_interface_state_to_disabled_(wrt_#2945877).patch
From:   Constantin Baranov const@mimas.ru
Desc:   Change default interface state to disabled (wrt #2945877)

Patch:  004_Restrict_igmp_reports_forwarding_to_upstream_interface_(wrt_#2912862).patch
From:   Stefan Becker stefan.becker@nokia.com
Desc:   Restrict igmp reports forwarding to upstream interface (wrt #2912862)

Patch:  101_zeroaltnet.patch
From:   http://wl500g.googlecode.com/svn-history/trunk/igmpproxy/001-zeroaltnet.patch
Desc:   

Patch:  102_timer.patch
From:   http://wl500g.googlecode.com/svn-history/trunk/igmpproxy/002-timer.patch
Desc:   

Patch:  150_igmpv3.patch
From:   http://wl500g.googlecode.com/svn-history/trunk/igmpproxy/050-igmpv3.patch
Desc:   

Patch:  160_multiple_origins.patch
From:   Ambroz Bizjak, http://wl500g.googlecode.com/svn-history/trunk/igmpproxy/060-multiple-origins.patch
Desc:   Support multiple multicast sources

Patch:  161_minor_fixes.patch
From:   cbean
Desc:   spelling fixes

Patch:  200_use_monotic_clock_instead_of_time_of_day.patch
From:   Jonas Gorski jonas.gorski@gmail.com
Desc:   use monotic clock instead of time of day

**Comment by pali** [comment]
On Tuesday 24 May 2016 09:00:55 cbean wrote:

> I tested version 17de79cc3ec459f5660616573d6edd0b2288b664 and it does not work.
> 
> It seems quickleave is needed for Telekom IPTV (Entertain).

Hi! That commit just change setpgrp() call with setpgid(0, 0) which is
equivalent. And I doubt it can broke something.

Can you bisect real commit?

**Comment by cbean** [comment]
I need to check older versions to make sure which version stopped working.

**Comment by cbean** [comment]
Okay let's start from here:
commit bcd7c648e86d97263c931de53a008c9629e7797e is working

**Comment by cbean** [comment]
Okay I narrowed it down, the latest version working is:

commit cfa6a5db1608903556eef95aaddd31f2e2f338fb

The version stopped working is:

commit 86c3637bfe94bbbd00b1b61fb7c29c125ac69d94

DESCRIPTION="Multicast Routing Daemon using only IGMP signalling (Internet Group Management Protocol)"
HOMEPAGE="https://github.com/pali/igmpproxy"
#COMMIT_ID="17de79cc3ec459f5660616573d6edd0b2288b664"       # not working
#COMMIT_ID="e3d661aade72c7619435f7c51833225b93512990"       # not working
#COMMIT_ID="8a74b9524ce1be9eaadd58e32cad653644344558"       # not working
#COMMIT_ID="86c3637bfe94bbbd00b1b61fb7c29c125ac69d94"       # not working
COMMIT_ID="cfa6a5db1608903556eef95aaddd31f2e2f338fb"        # not working
#COMMIT_ID="f0b483a2a02574c1e0ffde68b227c8c8bd689a7e"       # working
#COMMIT_ID="bcd7c648e86d97263c931de53a008c9629e7797e"       # working
SRC_URI="https://github.com/pali/${PN}/archive/${COMMIT_ID}.tar.gz  -> ${P}.tar.gz"

**Comment by cbean** [comment]
pali, also check this:

diff -urNp a/src/igmpproxy.h b/src/igmpproxy.h
--- a/src/igmpproxy.h   2013-05-31 12:47:22.000000000 +0200
+++ b/src/igmpproxy.h   2013-05-31 12:49:13.000000000 +0200
@@ -92,8 +92,8 @@ extern char     *send_buf;

 extern char     s1[];
 extern char     s2[];
-extern char        s3[];
-extern char        s4[];
+extern char     s3[];
+extern char     s4[];

diff -urNp a/src/request.c b/src/request.c
--- a/src/request.c 2011-06-16 11:49:05.000000000 +0200
+++ b/src/request.c 2013-05-31 12:48:14.000000000 +0200
@@ -100,7 +100,7 @@ void acceptGroupReport(uint32_t src, uin
    my_log(LOG_INFO, 0, "The group address %s may not be requested from this interface. Ignoring.", inetFmt(group, s1));
     } else {
         // Log the state of the interface the report was recieved on.
-        my_log(LOG_INFO, 0, "Mebership report was recieved on %s. Ignoring.",
-        my_log(LOG_INFO, 0, "Membership report was recieved on %s. Ignoring.",
           sourceVif->state==IF_STATE_UPSTREAM?"the upstream interface":"a disabled interface");
   }

**Comment by cbean** [comment]
Okay, found out the issue:

I had to add:

defaultdown

to igmpproxy.conf

Tested latest version and it is working, indeed.

Btw, you should make daemonize make optional since it detaches from init-systems i.e. openrc.
