### ISSUE TITLE
Becoming privbind-compatible?

### ISSUE THREAD

**Issue by Olivier-Boudeville** [pali/igmpproxy#15]
Hi,

Apparently the proxy cannot be used with privbind, in order to avoid running the server as root?
 $ privbind -u igmp-proxy /bin/igmpproxy /etc/igmpproxy.conf
igmpproxy: must be root

Indeed in https://github.com/pali/igmpproxy/blob/next/src/igmpproxy.c :
"""
// Chech that we are root
	if (geteuid() != 0) {
	   fprintf(stderr, "igmpproxy: must be root\n");
	   exit(1);
}

Would be neat if it could be done!

**Comment by pali** [comment]
igmpproxy needs to open and use raw socket. which can be done only by root or by user with some capability. maybe we can add that check for correct capability...

**Comment by Olivier-Boudeville** [comment]
Hello Pali,

Thanks for your answer (and, BTW, thanks for this nice tool as well)! 

I was thinking that privbind may work for RAW sockets too (as it does for Internet domain sockets cf https://github.com/JiriHorky/privbind/blob/master/README), but apparently not; with the root check commented out, knowing that the igmp-proxy user is a non-priviledged one, we have (on a gateway, run as root):
 $ privbind -n 10 -u igmp-proxy /usr/local/sbin/igmpproxy -v -v -d /etc/igmpproxy.conf
that fails with:
"""
[...]
Found config for enp4s0
Found config for enp2s0
IGMP socket open; Errno(1): Operation not permitted
"""
corresponding to:    
  if ( (MRouterFD  = socket(AF_INET, SOCK_RAW, IPPROTO_IGMP)) < 0 )

So, no, unless privbind is generalised to these socket settings (if it is possible at all), no way.
(reason behind these tests: paranoid gateway admins may prefer exposing a proxy with less rights than root ones; privbind works great to do the same for example with webservers binding to TCP port 80 - yet running as a non-root user).

**Comment by pali** [comment]
For security you have two options (or both together):
* Start igmpproxy as less privileged user with CAP_NET_RAW capability (see man 7 capabilities)
* Configure SELinux or AppArmor or Grsecurity for igmpproxy

**Comment by Olivier-Boudeville** [comment]
OK, thanks for these information - will try them!
