### ISSUE TITLE
consider tagging a new git release

### ISSUE THREAD

**Issue by anthraxx** [pali/igmpproxy#22]
Hey, it would be awesome if you can tag a new git release.
cheers

**Comment by fichtner** [comment]
Hello,

We are considering updating the FreeBSD port. Is there any chance to get a new version number greater than 0.1 ? :)


Thank you,
Franco

**Comment by pali** [comment]
Yes, I will try to look at it later in this or next week. Problem with license is finally fixed, so it is time to release fully GPL compatible igmpproxy source/binary.

**Comment by pali** [comment]
Done! New version 0.2 was released: https://github.com/pali/igmpproxy/releases/tag/0.2

**Comment by fichtner** [comment]
Awesome, thank you. Will there be release notes? An overview of your achievements would certainly be useful to have for future reference. 😊

**Comment by pali** [comment]
Whole changelog is available in uploaded tarball. Release notes with major changes are now available on github release page.

**Comment by anthraxx** [comment]
@pali wow, thats super awesome. extra special thanks for doing so. xmas gifts... yay :gift: :heart_eyes: :tada:
