### ISSUE TITLE
filter local multicast 239.255.255.250

### ISSUE THREAD

**Issue by poige** [pali/igmpproxy#54]
Why?

Is there anything wrong with that?

**Comment by pali** [comment]
Reference to discussion about this problem: https://github.com/pali/igmpproxy/commit/b445adbcbfa4b716e673ed55bfe53afc2f26baa8
And some proposed solutions: https://github.com/pali/igmpproxy/commit/b445adbcbfa4b716e673ed55bfe53afc2f26baa8#commitcomment-36374166

**Comment by poige** [comment]
I agree that it's better to have it configurable, rather than built-in.

**Comment by bb2020** [comment]
For those who are looking for a temporary solution: I install an obsolete version of `igmpproxy` on Openwrt (24kc device) to receive local SSDP. It is compatible with latest OS.

`opkg install https://downloads.openwrt.org/releases/17.01.0/packages/mips_24kc/base/
igmpproxy_0.1-10_mips_24kc.ipk`

**Comment by pali** [comment]
Reopening, this issue is not fixed, I just linked discussion about this issue. If you would like to work on solution for this problem, feel free to propose patches / pull requests.

**Comment by knightjoel** [comment]
Hi @pali, The patch below implements a new config option `allowssdp` which short circuits the check for the SSDP group. With this patch, I'm able to proxy reports for 239.255.255.250 between interfaces. If you think this is on the right track, I will fix up igmpproxy.conf(5) to mention this new config option.


```
--- src/config.c.orig   Sun Jan 10 14:10:07 2021
+++ src/config.c        Sun Jan 10 14:13:27 2021
@@ -196,6 +196,13 @@
             // Read next token...
             token = nextConfigToken();
             continue;
+        }
+        else if (strcmp("allowssdp", token)==0) {
+            my_log(LOG_DEBUG, 0, "Config: Will allow SSDP (239.255.255.250).");
+            commonConfig.allowSsdp = 1;
+
+            token = nextConfigToken();
+            continue;
         } else {
             // Unparsable token... Exit...
             closeConfigFile();
--- src/igmp.c.orig     Sun Jan 10 14:10:07 2021
+++ src/igmp.c  Sun Jan 10 14:13:27 2021
@@ -111,6 +111,8 @@
     struct igmpv3_grec *grec;
     int ipdatalen, iphdrlen, ngrec, nsrcs, i;

+    struct Config *config = getCommonConfig();
+
     if (recvlen < (int)sizeof(struct ip)) {
         my_log(LOG_WARNING, 0,
             "received packet too short (%u bytes) for IP header", recvlen);
@@ -122,7 +124,7 @@
     dst       = ip->ip_dst.s_addr;

     /* filter local multicast 239.255.255.250 */
-    if (dst == htonl(0xEFFFFFFA))
+    if (!config->allowSsdp && dst == htonl(0xEFFFFFFA))
     {
         my_log(LOG_NOTICE, 0, "The IGMP message was local multicast. Ignoring.");
         return;
--- src/igmpproxy.h.orig        Sun Jan 10 14:10:07 2021
+++ src/igmpproxy.h     Sun Jan 10 14:13:27 2021
@@ -179,6 +179,7 @@
     // Set if not detect new interface for down stream.
     unsigned short     defaultInterfaceState;  // 0: disable, 2: downstream
     //~ aimwang added done
+    unsigned short     allowSsdp;
 };

 // Holds the indeces of the upstream IF...
```

**Comment by pali** [comment]
@knightjoel: This should be handled in generic way, no just for one specific address, see my comment: https://github.com/pali/igmpproxy/commit/b445adbcbfa4b716e673ed55bfe53afc2f26baa8#commitcomment-36374166
