### ISSUE TITLE
Joining group more often

### ISSUE THREAD

**Issue by octavsly** [pali/igmpproxy#56]
With KPN in NL I have an issue that the multicast packet stop on the upstream interface after some minutes. 

Analyzing the traffic I have seen that the multicast client sends 
RECV V2 member report   from 192.168.10.2    to 224.0.251.110 
every 8 seconds. Since the group is already joined and the routing is active igmpproxy does not do anything.
If I force a leavegroup and joing group than I do not have the issue I mentioned. 

Therefore I have added in rttable.c

    // Send join message upstream, if the route has no joined flag...
    if(croute->upstrState != ROUTESTATE_JOINED) {
        // Send Join request upstream
        sendJoinLeaveUpstream(croute, 1);
    } else {
    	**//Octavian : ping pong between join/not join. This will ensure that the flow of data reaches the TV box
    	// otherwise after sime time ~5 minutes due to a lock of join on th eupstream interface the flow of data
    	// on the upstream interface stops.
    	sendJoinLeaveUpstream(croute, 0);
    	sendJoinLeaveUpstream(croute, 1);**
    }

This is definitely not the most elegant solution, but it works. Do you have a better solution? 

Is there a timeout for joining/leaving?

Thank you in advance for the answer,
Octavian

**Comment by tiba222** [comment]
The change you made should not be necessary, there is absolutely no valid reason to send a Leave immediately followed by a Join. Also I'm on the KPN / XS4ALL network in the Netherlands myself and do not recognize this issue.

On which platform are you using igmpproxy? I have seen this behavior before if firewall rules are missing. In pfSense for example you must explicitly allow IGMP **including protocol options** in both directions.

**Comment by octavsly** [comment]
Gentoo linux. Here are the relevant firewall rules.
 enp4s5.4 is the upstream interface. I have put more info in the last post of https://forum.telfort.nl/tv-338/iptv-routed-mode-settings-used-bridge-before-85768

SO relevant  firewall rules
```
Chain INPUT (policy DROP 4 packets, 144 bytes)

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source       destination         
  32M   40G ACCEPT     all  --  *      *       0.0.0.0/0    0.0.0.0/0    PKTTYPE = multicast

Chain OUTPUT (policy ACCEPT 47239 packets, 17M bytes)

NAT table:

Chain POSTROUTING (policy ACCEPT 1342K packets, 80M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 3431  262K MASQUERADE  all  --  *      enp4s5.4  0.0.0.0/0            0.0.0.0/0  
```         

The question is why does it take 5-7 minute for the stream to end? The ending means no UDP traffic anymore on upstream interface. So it looks like the iptv server stopped sending.

**Comment by tiba222** [comment]
If that are your only firewall rules for IGMP / multicast I think the problem is that you have no rule for accepting IGMP in the INPUT chain. That probably causes group specific queries from IPTV WAN to get dropped instead of answered resulting in the multicast stream to stop after about 5 minutes. 

This will also explain why sending the leave immediately followed by a join solves the issue, you with that modification just stopping and starting the stream yourself on every periodic report from the settopbox. Please make sure you have firewall rules for INPUT IGMP traffic from both directions and try again.

**Comment by octavsly** [comment]
Thanks for the answer. Indeed this seems logical. 
In the INPUT chain I was also accepting RELATED and ESTABLISHED (forgot to mention it before) but I presume for multicast traffic this is not enough since the incoming is neither related nor established.

I have added, and testing: 
```
Chain INPUT (policy DROP 0 packets, 0 bytes)
pkts bytes target     prot opt in     out source     destination
314K  423M ACCEPT     all  --  enp4s5.4 * 0.0.0.0/0  0.0.0.0/0   PKTTYPE = multicast
```

 enp4s5.4 is the WAN VLAN for IPTV

**Comment by octavsly** [comment]
That solved the problem. Thank you again. Any donate button?
