### ISSUE TITLE
MC-Router API already in use; Errno(98): Address already in use

### ISSUE THREAD

**Issue by fegauthier** [pali/igmpproxy#74]
Hi!

I'm using Debian 10 and I'm having this issue.

Jul 29 17:42:59 vyos igmpproxy[10347]: MC-Router API already in use; Errno(98): Address already in use

Does anybody know why?

This is my config file

```
quickleave

# Configuration for eth1.36 (upstream interface)
phyint eth1.36 upstream ratelimit 0 threshold 1
        altnet 224.0.0.0/8
        altnet 10.0.0.0/8

# Configuration for eth3 (downstream interface)
phyint eth3 downstream ratelimit 0 threshold 1
        altnet 192.168.5.0/24

```

Thanks!

**Comment by pali** [comment]
> Jul 29 17:42:59 vyos igmpproxy[10347]: MC-Router API already in use; Errno(98): Address already in use

It means that igmpproxy (or some other multicast routing daemon) is already running.

Only one instance of multicast routing daemon can be started at the same time.

**Comment by fegauthier** [comment]
Hi @pali 

Do you know where I can found the process that use the multicast routing deamon? When I do "ps aux", I found nothing about igmpproxy...

I'm using VyOS 1.3 that is based on Debian 10.

**Comment by pali** [comment]
I do not know how to identify such process. Maybe netstat could be usefull. I know these multicast routing daemons: smcroute, mrouted, igmpproxy.

**Comment by hommeabeil** [comment]
Hi, I just get couth with this myself. On debian10, a unit systemd exist and is started when you install the package. Simply run `systemctl stop igmpproxy` and you should be good to go.

**Comment by fegauthier** [comment]
I used it with VyOS which is based on Debian 10. The problem is fixed. There was another process that was using the MC-Router API. Thanks for your help!
