### ISSUE TITLE
Multicast broken in FreeBSD 12.x

### ISSUE THREAD

**Issue by Uglymotha** [pali/igmpproxy#75]
Hi,

Just to let you know, I have come across a serious issue with multicast on FreeBSD 12. Groups are joined, but never left, causing streams to keep running indefinitely, possibly saturating upstream links.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248512

**Comment by pali** [comment]
Based on discussion in bugzilla, that issue is in FreeBSD and was already fixed. So closing.
