### ISSUE TITLE
Compilation errors on OpenBSD

### ISSUE THREAD

**Issue by knightjoel** [pali/igmpproxy#78]
Hi. I see in #68 that there were recent issues with compiling on FreeBSD due to types like u_long and others not being defined. The same issue exists on OpenBSD. 

As @Uglymotha put it, this is coming back to the "*early or incorrect define of __POSIX_C_SOURCE (which is done in igmpproxy.c before including igmpproxy.h.*" If the definition of `_POSIX_C_SOURCE` is removed from igmpproxy.c and sys/cdefs.h on OpenBSD is allowed to define this and `__BSD_VISIBLE` on its own, u_long and related types get defined and everything is fine.

Why is `_POSIX_C_SOURCE` defined manually at all? Is that really necessary for any of igmpproxy's supported platforms? If it is, could that be moved to the platform specific os.h header?

And since this affected OpenBSD and FreeBSD, it would stand to reason that Dragonfly and NetBSD are also affected. I don't have the machinery to test either of them, unfortunately.

(Note there are a couple unrelated fixes needed to get 0.2.1 or 0.3 to compile on OpenBSD which I will create a PR for once this issue is settled.)

**Comment by pali** [comment]
This is bug in FreeBSD header files, I wrote description here: https://github.com/pali/igmpproxy/pull/69#issuecomment-629104763

If it affects also OpenBSD, have you reported this bug to OpenBSD project that they have broken header files? If not, please please report bug to OpenBSD instead of _random application_.

**Comment by pali** [comment]
`_POSIX_C_SOURCE` is standard macro for POSIX systems to ensure particular compatibility/visibility of some functions. I do not see nothing wrong with it.

But it is irrelevant to that FreeBSD issue as problem is somewhere else.

**Comment by knightjoel** [comment]
Ouch.

Respectfully, what you're suggesting is that a core header file that has defined `__BSD_VISIBLE` for 15 years in OpenBSD and almost 20 years in FreeBSD is incorrect because of a `#define` that is present in the igmpproxy code. I'll point out again that when `_POSIX_C_SOURCE` is not explicitly defined in the igmpproxy code, compilation succeeds on OpenBSD. It's hard to see what leg you have to stand on here in claiming that the operating systems are broken. Those projects are not going to "fix" a standard header file because of something that a third-party piece of software is doing.

To the point in #69 about FreeBSD's use of `u_long` in `struct rt_metrics`, it's clearly [documented](https://www.freebsd.org/cgi/man.cgi?query=rtentry&apropos=0&sektion=0&manpath=FreeBSD+12.2-RELEASE+and+Ports&arch=default&format=html) what headers beyond `net/route.h` need to be pulled in when using this struct (`sys/types.h` pulls in `sys/cdefs.h` which is where `__BSD_VISIBLE` gets defined). If you don't pull in those headers, yeah, bad things will happen.

Looking at the original commit (55dad738) which defined `_POSIX_C_SOURCE`, it looks like maybe it was done to satisfy a need on Linux? Would moving that define to os-linux.h not fill whatever need there is on Linux while also fixing the BSD issues?

**Comment by pali** [comment]
> Ouch.
> 
> Respectfully, what you're suggesting is that a core header file that has defined __BSD_VISIBLE for 15 years in OpenBSD and almost 20 years in FreeBSD is incorrect because of a #define that is present in the igmpproxy code.

Have you read my comment https://github.com/pali/igmpproxy/pull/69#issuecomment-629104763 ? Probably nobody hit this issue.

> what headers beyond net/route.h need to be pulled in when using this struct (sys/types.h pulls in sys/cdefs.h which is where __BSD_VISIBLE gets defined). If you don't pull in those headers, yeah, bad things will happen.

Have you read my comment https://github.com/pali/igmpproxy/pull/69#issuecomment-629104763 ?

They are using `u_long` even when it is not defined. Including any additional headers would not help in this situation.

**Comment by pali** [comment]
Have you tried compiling dummy program
```c
 #include <sys/types.h>
 #include <sys/socket.h>
 #include <net/route.h>
int main() { return 0; }
```
with `c99 -D_POSIX_C_SOURCE=200112L -O -o test test.c` command?

**Comment by knightjoel** [comment]
I'm not sure what you want to prove/disprove with that, however... No matter how `_POSIX_C_SOURCE` is defined--CLI or in the code--compilation fails. When it's not defined, that test program compiles.

**Comment by pali** [comment]
> I'm not sure what you want to prove/disprove with that

If compilation of above program fails then headers have bugs. Compilation should not fail on such simple program which just returns zero when some additional header files are included.

**Comment by knightjoel** [comment]
To anyone that might stumble across this issue who wants to run igmpproxy on OpenBSD: I'm submitting an updated port which will fix the compilation errors. Recommend you install from ports.

**Comment by pali** [comment]
I doubt that there is any bug... For 3 years nobody reported anything and now just there is one mentioned issue by @knightjoel where was proved that simple `int main() { return 0; }` cannot be compiled with same headers as in igmpproxy... ouch, so issue is for sure in `return 0;` code for sure.

Closing as reporter is unwilling to cooperate.
